apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nginxingresses.helm.operator-sdk
spec:
  group: helm.operator-sdk
  names:
    kind: NginxIngress
    listKind: NginxIngressList
    plural: nginxingresses
    singular: nginxingress
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
